### PR TITLE
Feature/myf 3 portal login

### PR DESCRIPTION
**Pull request by nehadubey2311**
Changes in the PR:

- Used LoginView to create login form and authentication of users
- Added a template 'login.html'
- Added a couple tests
- Updated app name in 'apps.py' as it was erroring out for me due to difference in app name

### CODE REVIEW

**Review by kelly-mcdougall — COMMENTED** [review]
This looks good! My one suggestion is to add 
`LOGIN_REDIRECT_URL = '/'`

to the base.py/settings file. At the moment it looks like UserLogin() is using the default redirect to 'accounts/profile'. This would redirect to the homepage, though perhaps the decision of where to redirect is still being worked out.

**Comment by nehadubey2311** [comment]
> This looks good! My one suggestion is to add `LOGIN_REDIRECT_URL = '/'`
> 
> to the base.py/settings file. At the moment it looks like UserLogin() is using the default redirect to 'accounts/profile'. This would redirect to the homepage, though perhaps the decision of where to redirect is still being worked out.

Thanks Kelly. I considered adding the redirect but wasn't sure what should I redirect to. I can redirect to root for now as you suggested or wait until Friday meeting to discuss what should be a better redirect page.

**Comment by madushag** [comment]
> redirect

I think we can redirect to the farm index page where a farmer can manage their farm listings. That app is in my PR branch at this point. I can merge it into Dev later today.

**Comment by nehadubey2311** [comment]
> > redirect
> 
> I think we can redirect to the farm index page where a farmer can manage their farm listings. That app is in my PR branch at this point. I can merge it into Dev later today.

I was thinking the same. For now I have updated the PR to add redirect to root as Kelly suggested. We can come back and update it while doing integration. Please review again so that we can merge it.

**Review by madushag — CHANGES_REQUESTED** [review]
Chris had advised me to exclude adding db.sqllite to the repo, so I would suggest doing the same from this PR. Otherwise, it looks good from my perspective.

**Comment by nehadubey2311** [comment]
> Chris had advised me to exclude adding db.sqllite to the repo, so I would suggest doing the same from this PR. Otherwise, it looks good from my perspective.

That is a great catch. I didn't even notice that file. Deleted from my branch now. However I also noticed it is already part of dev branch so we may have added it accidentally at some commit. However now that I removed from my branch that should hopefully fix it.

**Pull request merged**
